
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ModeToggle from "@/components/togleMode";
import { SidebarHeader, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import SideBarHeaderComponent from "@/components/sidebar-header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
      >
        <SidebarProvider>
      <AppSidebar />
      <div className="flex-1 flex flex-col relative">
        {/* Top header */}
        <div className="sticky z-10 right-0 top-0 w-full left-0">
          <SideBarHeaderComponent />
</div>
        <main className="flex-1 p-2 px-4">
          {children}
        </main>
      </div>
    </SidebarProvider>
 </ThemeProvider>
  );
}
